#!/usr/bin/env python3
"""
Calculate radial distribution functions (RDF) for center of mass of FA and MA cations
in perovskite structures generated by perovskite_poscar_creator.py

Usage: python calculate_cation_rdf.py <trajectory_file> [options]

Options:
  --rmax RMAX       Maximum distance for RDF calculation (default: 12.0 Å)
  --nbins NBINS     Number of bins for RDF (default: 200)
  --stride STRIDE   Use every STRIDE frames from trajectory (default: 1)
  --output OUTPUT   Output prefix for files (default: <input_basename>_rdf)
"""

import numpy as np
import sys
import os
import argparse
from ase.io import read
from collections import defaultdict
import matplotlib.pyplot as plt


# Atomic masses (in amu)
ATOMIC_MASSES = {
    'C': 12.011,
    'N': 14.007,
    'H': 1.008,
    'Pb': 207.2,
    'I': 126.904,
    'Br': 79.904
}


def identify_molecules(atoms):
    """
    Identify FA and MA molecules in the structure based on connectivity.
    
    FA (formamidinium): CH(NH2)2 - has 1 C, 2 N, 5 H (8 atoms total)
    MA (methylammonium): CH3NH3 - has 1 C, 1 N, 6 H (8 atoms total)
    
    Returns:
        fa_molecules: list of lists, each containing indices of atoms in an FA molecule
        ma_molecules: list of lists, each containing indices of atoms in an MA molecule
    """
    
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    cell = atoms.get_cell()
    pbc = atoms.get_pbc()
    
    # Find all C, N, H atoms (exclude Pb, I, Br)
    cation_indices = [i for i, s in enumerate(symbols) if s in ['C', 'N', 'H']]
    cation_symbols = [symbols[i] for i in cation_indices]
    cation_positions = positions[cation_indices]
    
    # Build connectivity graph based on distance cutoffs
    cutoff_CN = 1.5  # C-N bond distance cutoff (Å)
    cutoff_CH = 1.3  # C-H bond distance cutoff (Å)
    cutoff_NH = 1.2  # N-H bond distance cutoff (Å)
    
    def get_distance(pos1, pos2):
        """Calculate minimum image distance with PBC"""
        delta = pos2 - pos1
        if pbc.any():
            delta = delta - cell.lengths() * np.round(delta / cell.lengths())
        return np.linalg.norm(delta)
    
    # Build adjacency list
    adjacency = defaultdict(list)
    for i in range(len(cation_indices)):
        for j in range(i + 1, len(cation_indices)):
            dist = get_distance(cation_positions[i], cation_positions[j])
            
            si, sj = cation_symbols[i], cation_symbols[j]
            
            # Check if atoms are bonded
            is_bonded = False
            if (si == 'C' and sj == 'N') or (si == 'N' and sj == 'C'):
                if dist < cutoff_CN:
                    is_bonded = True
            elif (si == 'C' and sj == 'H') or (si == 'H' and sj == 'C'):
                if dist < cutoff_CH:
                    is_bonded = True
            elif (si == 'N' and sj == 'H') or (si == 'H' and sj == 'N'):
                if dist < cutoff_NH:
                    is_bonded = True
            
            if is_bonded:
                adjacency[i].append(j)
                adjacency[j].append(i)
    
    # Find connected components (molecules)
    visited = set()
    molecules = []
    
    def dfs(node, component):
        visited.add(node)
        component.append(node)
        for neighbor in adjacency[node]:
            if neighbor not in visited:
                dfs(neighbor, component)
    
    for i in range(len(cation_indices)):
        if i not in visited:
            component = []
            dfs(i, component)
            if len(component) >= 8:  # FA and MA both have 8 atoms
                molecules.append(component)
    
    # Classify molecules as FA or MA
    fa_molecules = []
    ma_molecules = []
    
    for mol in molecules:
        mol_symbols = [cation_symbols[i] for i in mol]
        n_C = mol_symbols.count('C')
        n_N = mol_symbols.count('N')
        n_H = mol_symbols.count('H')
        
        if len(mol) == 8 and n_C == 1 and n_H == 5:
            if n_N == 2:
                # FA: C, 2N, 5H
                fa_molecules.append([cation_indices[i] for i in mol])
            elif n_N == 1:
                # MA: C, 1N, 6H (but we counted 5H, might be 6H)
                ma_molecules.append([cation_indices[i] for i in mol])
        elif len(mol) == 8 and n_C == 1 and n_N == 1 and n_H == 6:
            # MA: C, 1N, 6H
            ma_molecules.append([cation_indices[i] for i in mol])
    
    return fa_molecules, ma_molecules


def calculate_center_of_mass(atoms, molecule_indices):
    """
    Calculate the center of mass for a molecule given atom indices.
    
    Args:
        atoms: ASE Atoms object
        molecule_indices: list of atom indices in the molecule
    
    Returns:
        com: center of mass position (3D array)
    """
    positions = atoms.get_positions()[molecule_indices]
    symbols = [atoms.get_chemical_symbols()[i] for i in molecule_indices]
    masses = np.array([ATOMIC_MASSES[s] for s in symbols])
    
    total_mass = np.sum(masses)
    com = np.sum(positions * masses[:, np.newaxis], axis=0) / total_mass
    
    return com


def calculate_rdf(positions, cell, rmax=12.0, nbins=100):
    """
    Calculate radial distribution function for a set of positions.
    
    Args:
        positions: Nx3 array of positions
        cell: ASE cell object
        rmax: maximum distance for RDF
        nbins: number of bins
    
    Returns:
        r: array of distances
        g_r: RDF values
    """
    n_particles = len(positions)
    
    if n_particles < 2:
        return np.linspace(0, rmax, nbins), np.zeros(nbins)
    
    # Create bins
    dr = rmax / nbins
    r_bins = np.linspace(0, rmax, nbins + 1)
    r = (r_bins[:-1] + r_bins[1:]) / 2
    hist = np.zeros(nbins)
    
    # Calculate volume
    volume = cell.volume
    
    # Calculate pairwise distances
    for i in range(n_particles):
        for j in range(i + 1, n_particles):
            # Apply minimum image convention
            delta = positions[j] - positions[i]
            delta = delta - cell.lengths() * np.round(delta / cell.lengths())
            dist = np.linalg.norm(delta)
            
            if dist < rmax:
                bin_idx = int(dist / dr)
                if bin_idx < nbins:
                    hist[bin_idx] += 2  # Count both i-j and j-i
    
    # Normalize RDF
    # g(r) = (number of pairs in shell) / (ideal gas density * shell volume * number of particles)
    rho = n_particles / volume  # number density
    
    for i in range(nbins):
        r_inner = r_bins[i]
        r_outer = r_bins[i + 1]
        shell_volume = (4.0 / 3.0) * np.pi * (r_outer**3 - r_inner**3)
        
        # Expected number of pairs in ideal gas
        n_ideal = rho * shell_volume * n_particles
        
        if n_ideal > 0:
            hist[i] = hist[i] / n_ideal
    
    return r, hist


def plot_rdf(r_values, rdf_data, output_prefix='rdf_cations'):
    """
    Plot RDF results as separate images for each pair.
    
    Args:
        r_values: distance array
        rdf_data: dictionary with keys 'FA-FA', 'MA-MA', 'FA-MA' and RDF arrays as values
        output_prefix: prefix for output files
    """
    colors = {'FA-FA': 'blue', 'MA-MA': 'red', 'FA-MA': 'green'}
    titles = {
        'FA-FA': 'RDF: FA-FA (Center of Mass)',
        'MA-MA': 'RDF: MA-MA (Center of Mass)',
        'FA-MA': 'RDF: FA-MA (Center of Mass)'
    }
    
    output_files = []
    
    # Create separate plot for each RDF
    for key in ['FA-FA', 'MA-MA', 'FA-MA']:
        if key in rdf_data and rdf_data[key] is not None:
            plt.figure(figsize=(10, 6))
            
            plt.plot(r_values, rdf_data[key], 
                    color=colors[key], linewidth=2.5)
            
            plt.xlabel('r (Å)', fontsize=14)
            plt.ylabel('g(r)', fontsize=14)
            plt.title(titles[key], fontsize=16)
            plt.grid(True, alpha=0.3)
            plt.xlim(0, r_values[-1])
            plt.ylim(bottom=0)
            plt.tight_layout()
            
            # Save individual figure
            output_file = f'{output_prefix}_{key}.png'
            plt.savefig(output_file, dpi=300)
            output_files.append(output_file)
            print(f"RDF plot saved to: {output_file}")
            
            plt.close()
    
    # Create combined plot for comparison
    if len(rdf_data) > 0:
        plt.figure(figsize=(10, 6))
        
        for key in ['FA-FA', 'MA-MA', 'FA-MA']:
            if key in rdf_data and rdf_data[key] is not None:
                plt.plot(r_values, rdf_data[key], label=key, 
                        color=colors[key], linewidth=2)
        
        plt.xlabel('r (Å)', fontsize=14)
        plt.ylabel('g(r)', fontsize=14)
        plt.title('Radial Distribution Functions - Cation Centers of Mass', fontsize=16)
        plt.legend(fontsize=12)
        plt.grid(True, alpha=0.3)
        plt.xlim(0, r_values[-1])
        plt.ylim(bottom=0)
        plt.tight_layout()
        
        # Save combined figure
        output_file = f'{output_prefix}_combined.png'
        plt.savefig(output_file, dpi=300)
        output_files.append(output_file)
        print(f"Combined RDF plot saved to: {output_file}")
        
        # Show combined plot
        plt.show()
    
    return output_files


def save_rdf_data(r_values, rdf_data, output_prefix='rdf_cations'):
    """
    Save RDF data to text file.
    
    Args:
        r_values: distance array
        rdf_data: dictionary with RDF data
        output_prefix: prefix for output files
    """
    output_file = f'{output_prefix}.dat'
    
    with open(output_file, 'w') as f:
        f.write("# Radial Distribution Functions for Cation Centers of Mass\n")
        f.write("# r(Å)    g_FA-FA(r)    g_MA-MA(r)    g_FA-MA(r)\n")
        
        for i, r in enumerate(r_values):
            line = f"{r:10.6f}"
            for key in ['FA-FA', 'MA-MA', 'FA-MA']:
                if key in rdf_data and rdf_data[key] is not None:
                    line += f"  {rdf_data[key][i]:12.8f}"
                else:
                    line += f"  {0.0:12.8f}"
            f.write(line + "\n")
    
    print(f"RDF data saved to: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Calculate RDF for center of mass of FA and MA cations in perovskite structures'
    )
    parser.add_argument('trajectory', type=str, help='Trajectory file (XYZ, TRAJ, etc.)')
    parser.add_argument('--rmax', type=float, default=12.0, 
                       help='Maximum distance for RDF calculation (default: 12.0 Å)')
    parser.add_argument('--nbins', type=int, default=200,
                       help='Number of bins for RDF (default: 200)')
    parser.add_argument('--stride', type=int, default=1,
                       help='Use every STRIDE frames from trajectory (default: 1)')
    parser.add_argument('--output', type=str, default=None,
                       help='Output prefix for files (default: <input_basename>_rdf)')
    
    args = parser.parse_args()
    
    # Auto-generate output prefix from input filename if not provided
    if args.output is None:
        basename = os.path.splitext(os.path.basename(args.trajectory))[0]
        args.output = f"{basename}_rdf"
    
    print(f"Reading trajectory from: {args.trajectory}")
    print(f"Output prefix: {args.output}")
    print(f"RDF parameters: rmax={args.rmax} Å, nbins={args.nbins}, stride={args.stride}")
    
    # Read trajectory
    try:
        trajectory = read(args.trajectory, index=f'::{args.stride}')
        if not isinstance(trajectory, list):
            trajectory = [trajectory]
        print(f"Successfully read {len(trajectory)} frames")
    except Exception as e:
        print(f"Error reading trajectory file: {e}")
        sys.exit(1)
    
    # Initialize accumulators for RDF
    rdf_fa_fa_sum = None
    rdf_ma_ma_sum = None
    rdf_fa_ma_sum = None
    n_frames = 0
    r_values = None
    
    # Process each frame
    for frame_idx, atoms in enumerate(trajectory):
        
        # Identify molecules
        fa_molecules, ma_molecules = identify_molecules(atoms)
        
        # Calculate centers of mass
        fa_coms = np.array([calculate_center_of_mass(atoms, mol) for mol in fa_molecules])
        ma_coms = np.array([calculate_center_of_mass(atoms, mol) for mol in ma_molecules])
        
        cell = atoms.get_cell()
        
        # Calculate RDFs for this frame
        if len(fa_coms) >= 2:
            r, g_fa_fa = calculate_rdf(fa_coms, cell, rmax=args.rmax, nbins=args.nbins)
            if rdf_fa_fa_sum is None:
                rdf_fa_fa_sum = g_fa_fa
                r_values = r
            else:
                rdf_fa_fa_sum += g_fa_fa
        
        if len(ma_coms) >= 2:
            r, g_ma_ma = calculate_rdf(ma_coms, cell, rmax=args.rmax, nbins=args.nbins)
            if rdf_ma_ma_sum is None:
                rdf_ma_ma_sum = g_ma_ma
                if r_values is None:
                    r_values = r
            else:
                rdf_ma_ma_sum += g_ma_ma
        
        if len(fa_coms) >= 1 and len(ma_coms) >= 1:
            # For FA-MA, combine positions
            combined_positions = np.vstack([fa_coms, ma_coms])
            n_fa = len(fa_coms)
            n_ma = len(ma_coms)
            
            # Calculate cross-correlation RDF
            dr = args.rmax / args.nbins
            r_bins = np.linspace(0, args.rmax, args.nbins + 1)
            r = (r_bins[:-1] + r_bins[1:]) / 2
            hist = np.zeros(args.nbins)
            
            for i in range(n_fa):
                for j in range(n_ma):
                    delta = ma_coms[j] - fa_coms[i]
                    delta = delta - cell.lengths() * np.round(delta / cell.lengths())
                    dist = np.linalg.norm(delta)
                    
                    if dist < args.rmax:
                        bin_idx = int(dist / dr)
                        if bin_idx < args.nbins:
                            hist[bin_idx] += 1
            
            # Normalize
            volume = cell.volume
            rho_ma = n_ma / volume
            
            for i in range(args.nbins):
                r_inner = r_bins[i]
                r_outer = r_bins[i + 1]
                shell_volume = (4.0 / 3.0) * np.pi * (r_outer**3 - r_inner**3)
                n_ideal = rho_ma * shell_volume * n_fa
                
                if n_ideal > 0:
                    hist[i] = hist[i] / n_ideal
            
            if rdf_fa_ma_sum is None:
                rdf_fa_ma_sum = hist
                if r_values is None:
                    r_values = r
            else:
                rdf_fa_ma_sum += hist
        
        n_frames += 1
    
    print(f"\nProcessed {n_frames} frames")
    
    # Average RDFs
    rdf_data = {}
    if rdf_fa_fa_sum is not None:
        rdf_data['FA-FA'] = rdf_fa_fa_sum / n_frames
        print(f"FA-FA RDF calculated successfully")
    else:
        print("Warning: Could not calculate FA-FA RDF (need at least 2 FA molecules)")
    
    if rdf_ma_ma_sum is not None:
        rdf_data['MA-MA'] = rdf_ma_ma_sum / n_frames
        print(f"MA-MA RDF calculated successfully")
    else:
        print("Warning: Could not calculate MA-MA RDF (need at least 2 MA molecules)")
    
    if rdf_fa_ma_sum is not None:
        rdf_data['FA-MA'] = rdf_fa_ma_sum / n_frames
        print(f"FA-MA RDF calculated successfully")
    else:
        print("Warning: Could not calculate FA-MA RDF (need at least 1 FA and 1 MA molecule)")
    
    if not rdf_data:
        print("Error: No RDF data could be calculated")
        sys.exit(1)
    
    # Save and plot results
    save_rdf_data(r_values, rdf_data, output_prefix=args.output)
    plot_rdf(r_values, rdf_data, output_prefix=args.output)
    
    print("\nDone!")


if __name__ == "__main__":
    main()
